# Generated by Django 4.2.11 on 2024-05-25 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseoutline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='outline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courseoutline.outline'),
        ),
    ]
