# Generated by Django 4.2.11 on 2024-05-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseoutline', '0002_alter_assessment_outline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='outcomes',
        ),
    ]
