# Generated by Django 4.2.11 on 2024-05-26 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseoutline', '0003_remove_assessment_outcomes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='name',
            new_name='method',
        ),
    ]
