# Generated by Django 4.2.11 on 2024-05-29 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseoutline', '0005_alter_assessment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outline',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courseoutline.course'),
        ),
    ]
